import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { API_VERSION, CATEGORY_QUERIES, MAX_CANDIDATES, MIN_STARS, OUTPUT_LIMIT } from './config';
import { delay, getLatestRelease, getStarHistory, searchRepositories, type GitHubRepo } from './github';
import { enrichRepository } from './scoring';

type Category = (typeof CATEGORY_QUERIES)[number]['category'];
type Candidate = { repo: GitHubRepo; categories: Set<Category> };

const candidates = new Map<string, Candidate>();

const previousStars = new Map<string, number>();
try {
  const previous = JSON.parse(await readFile(resolve('public/data/repositories.json'), 'utf8')) as { repositories?: Array<{ fullName: string; stars: number }> };
  for (const repo of previous.repositories ?? []) previousStars.set(repo.fullName, repo.stars);
} catch {
  // First run or invalid previous snapshot: Star History daily bucket remains the fallback for 24H.
}

for (const group of CATEGORY_QUERIES) {
  const term = group.terms[0];
  for (const band of [`stars:${MIN_STARS}..999`, 'stars:1000..20000']) {
    const query = `${term} in:name,description,topics ${band} archived:false`;
    try {
      const repos = await searchRepositories(query);
      for (const repo of repos) {
        const existing = candidates.get(repo.full_name);
        if (existing) existing.categories.add(group.category);
        else candidates.set(repo.full_name, { repo, categories: new Set([group.category]) });
      }
    } catch (error) {
      console.warn(`[search] ${group.category} ${band}:`, error instanceof Error ? error.message : error);
    }
    await delay(550);
  }
}

const selected = [...candidates.values()]
  .filter(({ repo }) => !repo.archived && !repo.fork && repo.stargazers_count >= MIN_STARS)
  .sort((a, b) => new Date(b.repo.pushed_at).getTime() - new Date(a.repo.pushed_at).getTime())
  .slice(0, MAX_CANDIDATES);

console.log(`Discovered ${candidates.size} unique repositories; checking history for ${selected.length}.`);

const withHistory: Array<{ candidate: Candidate; weeks: Awaited<ReturnType<typeof getStarHistory>> }> = [];
for (let i = 0; i < selected.length; i += 5) {
  const batch = selected.slice(i, i + 5);
  const results = await Promise.all(batch.map(async (candidate) => {
    try {
      const weeks = await getStarHistory(candidate.repo.full_name);
      return weeks.length ? { candidate, weeks } : null;
    } catch (error) {
      console.warn(`[history] ${candidate.repo.full_name}:`, error instanceof Error ? error.message : error);
      return null;
    }
  }));
  withHistory.push(...results.filter((value): value is NonNullable<typeof value> => value !== null));
  await delay(280);
}

let enriched = withHistory.map(({ candidate, weeks }) => enrichRepository(candidate.repo, [...candidate.categories], weeks, null));
enriched.sort((a, b) => b.earlySignalScore - a.earlySignalScore);

const releaseMap = new Map<string, Awaited<ReturnType<typeof getLatestRelease>>>();
for (let i = 0; i < Math.min(35, enriched.length); i += 5) {
  const batch = enriched.slice(i, i + 5);
  const releases = await Promise.all(batch.map(async (item) => {
    try { return [item.fullName, await getLatestRelease(item.fullName)] as const; }
    catch { return [item.fullName, null] as const; }
  }));
  releases.forEach(([fullName, release]) => releaseMap.set(fullName, release));
  await delay(220);
}

enriched = withHistory.map(({ candidate, weeks }) => {
  const item = enrichRepository(candidate.repo, [...candidate.categories], weeks, releaseMap.get(candidate.repo.full_name) ?? null);
  const previous = previousStars.get(item.fullName);
  return previous === undefined ? item : { ...item, star24h: Math.max(0, item.stars - previous) };
});
enriched.sort((a, b) => b.earlySignalScore - a.earlySignalScore);
const outputRepos = enriched.slice(0, OUTPUT_LIMIT);

const data = {
  generatedAt: new Date().toISOString(),
  source: {
    mode: 'live' as const,
    apiVersion: API_VERSION,
    note: 'Generated by GitHub Actions using Repository Search and privacy-safe Star History REST API.',
  },
  summary: {
    scannedRepositories: selected.length,
    qualifiedRepositories: outputRepos.filter((repo) => repo.earlySignalScore >= 65).length,
    fastest24hRepo: [...outputRepos].sort((a, b) => b.star24h - a.star24h)[0]?.fullName ?? null,
    averageSignal: outputRepos.length ? Math.round(outputRepos.reduce((sum, repo) => sum + repo.earlySignalScore, 0) / outputRepos.length) : 0,
  },
  repositories: outputRepos,
};

const outputPaths = [
  resolve('public/data/repositories.json'),
  resolve('docs/data/repositories.json'),
];
for (const outputPath of outputPaths) {
  await mkdir(dirname(outputPath), { recursive: true });
  await writeFile(outputPath, `${JSON.stringify(data, null, 2)}\n`);
  console.log(`Wrote ${outputRepos.length} repositories to ${outputPath}.`);
}
